### ISSUE TITLE
Firefox required by hack1.py but not installed in box

### ISSUE THREAD

**Issue by vTide** [shantnu/PythonForHackers#2]
During the run of hack1.py, the following error message was returned:

`Traceback (most recent call last):
  File "./hack1.py", line 103, in <module>
    driver = webdriver.Firefox()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/webdriver.py", line 54, in __init__
    self.binary = FirefoxBinary()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 49, in __init__
    self._start_cmd = self._get_firefox_start_cmd()
  File "/usr/local/lib/python3.4/dist-packages/selenium/webdriver/firefox/firefox_binary.py", line 161, in _get_firefox_start_cmd
    " Please specify the firefox binary location or install firefox")
RuntimeError: Could not find firefox in your system PATH. Please specify the firefox binary location or install firefox`

-----
When I try using apt to install firefox, I get the following error:

`vagrant@vagrant-ubuntu-trusty-32:/vagrant$ sudo apt install firefox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 firefox : Depends: libstartup-notification0 (>= 0.8) but it is not installable
           Recommends: xul-ext-ubufox but it is not going to be installed
           Recommends: libdbusmenu-glib4 but it is not going to be installed
           Recommends: libdbusmenu-gtk4 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.`

Please advise?

**Comment by shantnu** [comment]
Can you try this before installing firefox:

sudo apt-get update

Then install firefox.
